baseURL = 'https://federicomazzei.com.ar/'
#baseURL = 'http://localhost:1313/'
languageCode = 'es'
title = 'Federico Mazzei'
theme = 'github-style'
defaultContentLanguage = 'es'

pygmentsCodeFences = true
pygmentsUseClasses = true

# Esto sirve para que al hacer el render de .md a .html tenga en cuenta los tags html
[markup.goldmark.renderer]
unsafe = true
hardWraps = true

[frontmatter]
date = ['date', 'publishdate', 'pubdate', 'published', 'lastmod', 'modified']
expiryDate = ['expirydate', 'unpublishdate']
lastmod = [':git', 'lastmod', 'modified', 'date', 'publishdate', 'pubdate', 'published']
publishDate = ['publishdate', 'pubdate', 'published', 'date']

# [frontmatter]
#    lastmod = ["lastmod", ":fileModTime", ":default"]

# Esto permite que respete el publishDate
# enableGitInfo = true # No me funcionó como yo esperaba

[params]
    author = "Federico Mazzei"
    description = "El sitio de federico mazzei"
    subtitle = 'Un desarrollador web que día a día trata de mejorar'
    github = "fideo"
    facebook = "mazzeifederico"
    twitter = "fideox"
    linkedin = "federicomazzei"
    instagram = "fideox"
    #tumblr = "MeiK2333"
    email = "federicomazzei@gmail.com"
    url = "https://federicomazzei.com.ar/"
    keywords = "linux, vim, debian, ubuntu, docker, tecnología, comandos, git, blog, google analytics, federico mazzei"
    rss = true
    lastmod = true
    favicon = "/images/avatar.jpg"
    avatar = "/images/avatar.jpg"
    headerIcon = "/images/github-mark-white.png"
    location = "Argentina"
    userStatusEmoji = "😀"
    enableGitalk = true
    enableSearch = true
    [params.contact]
        email = 'federicomazzei@gmail.com'
        phone = '+54 9 11 2630-1170'


    [params.gitalk]
        clientID = "Ov23licCHTBOFJdZMIFm" # Your client ID
        clientSecret = "0f26adbf7edc171c9b848d55ec0aa9548f27f011" # Your client secret
        repo = "blog-comments" # ：xxxx.github.io
        owner = "fideo" # 您的GitHub ID
        admin = "fideo" # 您的GitHub ID
        id = "location.pathname" # ID
        labels = "gitalk" # Github issue labels. If you used to use Gitment, you can change it
        perPage = 15 # Pagination size, with maximum 100.
        pagerDirection = "last" # Comment sorting direction, available values are 'last' and 'first'.
        createIssueManually = true #(issue)
        distractionFreeMode = false # Enable hot key (cmd|ctrl + enter) submit comment.
        proxy = "https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token" #

    [[params.links]]
        title = "Link de mi repositorio GitHub"
        href = "https://github.com/fideo"
    [[params.links]]
        title = "Link a fideox.dev.ar"
        href = "https://fideox.dev.ar"

[services]
    [services.googleAnalytics]
    ID = "G-VS1RSDN0CD"

[outputs]
home = ["html", "json"]

[outputFormats.json]
mediaType = "application/json"
baseName = "index"
isPlainText = false